// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	DeleteAccount(ctx context.Context, id int64) error
	GetAccountById(ctx context.Context, id int64) (Account, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Account, error)
	GetAccounts(ctx context.Context, arg GetAccountsParams) ([]Account, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetIncomingTransfersByAccountId(ctx context.Context, arg GetIncomingTransfersByAccountIdParams) ([]Transfer, error)
	GetOutgoingTransfersByAccountId(ctx context.Context, arg GetOutgoingTransfersByAccountIdParams) ([]Transfer, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	TransferMoney(ctx context.Context, arg TransferMoneyParams) (Account, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error
}

var _ Querier = (*Queries)(nil)
