# This workflow will build a golang project

name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: shiba
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-versions: ^1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/4.18.1/migrate.linux-amd64.tar.gz | tar xzv
        sudo mv migrate.linux-amd64 /usr/bin/
        which migrate

    - name: Migrate DB
      run: make migrateup

    - name: Test
      run: make test

