# This workflow will build a golang project

name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-versions: ^1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test

